version: '3'

services:
    backend:
        build:
            dockerfile: ./fastgraphic/Dockerfile
            context: .

        image: fastgraphic_backend
        container_name: fastgraphic_backend
        volumes:
            - ./fastgraphic:/app
        ports:
            - "8000:8000"
