version: '3.7'

services:
    backend:
        build: fastgraphic
        restart: ${RESTART:-no}
        volumes:
            - ./:/app
        working_dir: /app/fastgraphic
        ports:
            - "${BACKEND_HOST_PORT}8000"
        stdin_open: true
        tty: true
        command: ${RUNSERVER:-/bin/bash}
