# Generated by Django 3.1.4 on 2021-01-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('finished', 'Finished')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
