# Generated by Django 3.1.4 on 2020-12-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
