# Generated by Django 3.1.4 on 2021-01-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201224_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
