# Generated by Django 3.1.4 on 2020-12-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201223_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='item',
        ),
    ]
