# Generated by Django 3.1.4 on 2020-12-24 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_sale_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.saleproduct'),
            preserve_default=False,
        ),
    ]
