# Generated by Django 3.1.4 on 2021-01-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_employee_is_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_product',
            field=models.BooleanField(default=False),
        ),
    ]
