# Generated by Django 3.1.4 on 2021-02-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_product_is_high_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('money', 'Dinheiro'), ('credit-card', 'Cartão de Crédito'), ('debit-card', 'Cartão de Débito')], default='money', max_length=20),
        ),
    ]
