# Generated by Django 3.1.4 on 2021-02-17 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_sale_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterModelOptions(
            name='saleproduct',
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_machine',
            field=models.BooleanField(default=False, verbose_name='Máquina'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(
                choices=[
                    ('seller', 'Vendedor(a)'),
                    ('administrator', 'Administrador(a)'),
                ],
                max_length=20,
                verbose_name='Cargo',
            ),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Funcionario',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(
                max_length=30, unique=True, verbose_name='Código'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Descrição'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_high_demand',
            field=models.BooleanField(
                default=False, verbose_name='Alta de demanda'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.FloatField(
                blank=True, null=True, verbose_name='Desconto'
            ),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='application.employee',
                verbose_name='Funcionario',
            ),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('money', 'Dinheiro'),
                    ('credit-card', 'Cartão de Crédito'),
                    ('debit-card', 'Cartão de Débito'),
                ],
                default='money',
                max_length=20,
                verbose_name='Forma de pagamento',
            ),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='application.product',
                verbose_name='Produto',
            ),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='application.sale',
                verbose_name='Venda',
            ),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='unit_price',
            field=models.FloatField(
                blank=True, null=True, verbose_name='Preço unitário'
            ),
        ),
    ]
