# Generated by Django 3.1.4 on 2021-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210217_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Criado em'
            ),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_change',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Atualizado em'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Criado em'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_change',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Atualizado em'
            ),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Criado em'
            ),
        ),
        migrations.AlterField(
            model_name='sale',
            name='last_change',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Atualizado em'
            ),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Criado em'
            ),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='last_change',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Atualizado em'
            ),
        ),
    ]
